### ISSUE TITLE
error when opening the token image

### ISSUE THREAD

**Issue by 1combo2** [MrPrimate/vtta-tokenizer#6]
This is what comes up when I try to open a image on a new token.
Running latest Foundry VTT 0.7.7
![image](https://user-images.githubusercontent.com/75395919/100935359-c18bbd00-34ce-11eb-85da-f3bc82e71d78.png)

**Comment by wleung85** [comment]
I've seen a similar problem occur after creating the token and image, having the Tokenizer save them to the server, and then moving the files. I fixed that by re-pointing the avatar and token images to the files after I moved them.

If the above doesn't describe what happened to you, can you give steps on how to recreate this problem?

**Comment by laurieathey** [comment]
I'm having the same error but in my case I've added tokens I've never used to the map before, and then went to set up an image for them and got the above error. 
EG:
![image](https://user-images.githubusercontent.com/11553364/102328196-0ad81400-3f87-11eb-865b-14beefcc5886.png)
I've never created a ghastly bear image so I don't know what it's looking for but it's not gonna find it. I suspect that's the problem. Any new tokens (not set up before) seem to be looking for the image before it's there instead of using the one that's assigned. To be clear: Old ones, already set up, work.

**Comment by grankless** [comment]
Also having this exact same issue. Extremely annoying and gives errors sometimes upon rendering a map.

**Comment by Unikatze** [comment]
Same issue. 
I've managed to workaround it by closing and reopening the token editor. 
Still very annoying and seems the Module is abandoned.
